nginx:
  container_name: nginx-test
  image: nginx-test
  ports:
    - 83:80
    - 444:443
  volumes:
    - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./nginx/certs:/etc/nginx/certs
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/log:/var/log/nginx
    - ./nginx/www/html:/var/www/html
    - ./nginx/www/404:/var/www/404/

  #restart: always
